### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by eli-sauvage** [Omega-Numworks/Omega-Themes#12]
![image](https://user-images.githubusercontent.com/36312455/72387406-c3685880-3723-11ea-822a-6e6e9abe75f3.png)
Hi, what am I doing wrong?

**Comment by quentinguidee** [comment]
Oops sorry, now the theme is installed during the compilation. So, when you compile Omega, you must do `make USERNAME="" OMEGA_THEME=epsilon_light`

I'll edit the README.md file as soon as possible 😉

**Comment by eli-sauvage** [comment]
thanks

**Comment by quentinguidee** [comment]
Don't hesitate to reopen this issue if you have any problems ;)
