### ISSUE TITLE
Error when typing "python themes_manager.py omega_dark"

### ISSUE THREAD

**Issue by EchOka** [Omega-Numworks/Omega-Themes#15]
#### Describe the bug
Hey there, i saw we can change the theme of the numworks into a dark theme, which interest me a lot. I tried to do it, but when writing "python themes_manager.py omega_dark" in the terminal, i get this:

Traceback (most recent call last):
  File "themes_manager.py", line 132, in <module>
    main(args)
  File "themes_manager.py", line 99, in main
    data = get_data(args.theme)
  File "themes_manager.py", line 21, in get_data
    with open(os.path.dirname(os.path.realpath(__file__)) + os.path.sep + "themes" + os.path.sep + theme + ".json", "r") as json_file:
IOError: [Errno 2] No such file or directory: '/home/echo/epsilon/Omega/themes/themes/Omega.json'

If i try to write "python themes_manager.py -1", i get this:

Traceback (most recent call last):
  File "themes_manager.py", line 132, in <module>
    main(args)
  File "themes_manager.py", line 99, in main
    data = get_data(args.theme)
  File "themes_manager.py", line 21, in get_data
    with open(os.path.dirname(os.path.realpath(__file__)) + os.path.sep + "themes" + os.path.sep + theme + ".json", "r") as json_file:
IOError: [Errno 2] No such file or directory: '/home/echo/epsilon/Omega/themes/themes/-1.json'

I'm not a expert, but i know it means it's bad. The thing is I don't really know why ^^'
Sorry if I'm just a dumbass and that it was just something i didn't get. Still hope i'll get an answer tho.

#### Environment
Omega version : 1.18.5-0

**Comment by EncryptCrystal** [comment]
Try with python "themes_manager.py <omega_dark>" :)
Ask your futurs questions on our Discord : https://discord.gg/JYhtnMB

**Comment by EchOka** [comment]
No such file or directory found :/ (thx for the fast answer still)

**Comment by quentinguidee** [comment]
Sorry, the readme is not updated with the latest Omega-Themes. Now, you should use the `OMEGA_THEME=omega_dark` flag during the compilation.

(See #16)
